### ISSUE TITLE
"Couldn't to connect to rvd(err:13)" when using non-root user

### ISSUE THREAD

**Issue by PeterTKY** [riboseinc/rvc#251]
After I installed rvc (osx High Sierra) following the instructions (tried both brew install and build from the repo), it simply couldn't connect to rvd giving out an error message:

> Couldn't to connect to rvd(err:13)

Am I missing anything?

**Comment by ronaldtse** [comment]
1. It sounds like RVD isn’t running. Can you “ps aux” to check? 

2. Check also if RVD actually can be run by itself because the configuration syntax has changed to Nereon format.  

3. Remember RVD has to be run as root, so ensure that you’ve run the necessary scripts as displayed by brew install. (And do not manually install because it is quite complicated to get all the details right)

**Comment by PeterTKY** [comment]
1.
> $ ps aux | grep rvc
peter_tam        15027   0.0  0.0  4258468    188 s000  R+   11:05AM   0:00.00 grep rvc
root             14832   0.0  0.0  4336384   1420   ??  Ss   10:50AM   0:00.69 /opt/rvc/bin/rvd

> $ ps aux | grep rvd
peter_tam        15041   0.0  0.0  4267768    892 s000  S+   11:06AM   0:00.00 grep rvd
root             14832   0.0  0.0  4336384   1420   ??  Ss   10:50AM   0:00.73 /opt/rvc/bin/rvd

2. No idea of how to check

3. I have followed all the instructions displayed, no luck...

**Comment by PeterTKY** [comment]
RVC works as long as I run `sudo rvc status all` rather than `rvc status all`.

`rvc status all`:
```
rvc status all
Couldn't to connect to rvd(err:13)
```

`sudo rvc status all`:
```
... normal output ...
```

@jjr840430 could you help fix this?

**Comment by PeterTKY** [comment]
Superseded by https://github.com/riboseinc/rvc/issues/252.
